name: govulncheck
on: 
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  govulncheck:
    name: govulncheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
      - id: govulncheck
        uses: golang/govulncheck-action@v1
        with:
          go-package: ./...
          repo-checkout: false
          go-version-file: go.mod
          go-version-input: ""
